server:
  port: 8080
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://47.107.249.42:3306/demo?serverTimezone=GMT%2B8&useSSL=false             # 数据库名称服务器地址禁止暴露
    username: root
    password: root
  thymeleaf:
    encoding: utf-8
    suffix: .html
    cache: false
  redis:
    host: 47.107.249.42
    port: 6379
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
    timeout: 10000s
  servlet:
    multipart:
      enabled: true
      max-file-size: 19MB
      max-request-size: 100MB
  elasticsearch:
    rest:
      uris: 47.107.249.42:9200
logging:
  level:
    com.tianling.blog.dao: debug

mybatis-plus:
  configuration:
    jdbc-type-for-null: null
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mybatis/*.xml
